### ISSUE TITLE
Can't print to 4"x6" paper 

### ISSUE THREAD

**Issue by ee0jmt** [porkbuns/shmile#45]
I'm trying to print the photo to 4"x6" photo paper. I have set up the default paper size on my printer settings (Mac), but the printer keeps reporting wrong paper size. 

Just wondering if anyone else has managed to do this.

**Comment by ee0jmt** [comment]
Managed to solve this. Its not a problem with the project!

I had to set the default printer settings using the web interface on the Mac:

http://127.0.0.1:631/printers_

**Comment by andrewhao** [comment]
Great, glad it worked!
